[package]
name = "rg"
version = "0.1.0"
authors = ["serprex"]

[dependencies]
rand = "0.3"
fnv = "1.0"
termios = "0.2"
specs = "0.7"
smallvec = "0.2"
x1b = "0.5.1"
#x1b = { path = "../x1b", version = "*" }

[profile.dev]
codegen-units = 2
